services:
  - type: web
    name: django-channels-counter
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne counter.asgi:application --port $PORT --bind 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: REDIS_URL
        fromService:
          type: redis
          name: counter-redis
          property: connectionString

  - type: redis
    name: counter-redis
    ipAllowList: [] # only allow internal connections
    plan: free
